name: Lint and build platformio
on:
  push:
    branches: 
      - '*'
  pull_request:

jobs:
  cpp_style_check:
    runs-on: ubuntu-latest
    name: Check C++ Style
    steps:
    - name: Checkout this commit
      uses: actions/checkout@v2
    - name: Run style checks
      uses: coleaeason/actions-uncrustify@v1
   
  install_platformio_and_build_watering_node:
    runs-on: ubuntu-latest
    needs: [cpp_style_check]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2.2.1

    - name: Install pio and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO build on selected platforms
      run: platformio run 
